# codegen_ev3.py

COLOUR_MAP = {
    'red': 5, 'green': 3, 'blue': 2, 'yellow': 4,
    'white': 6, 'black': 1, 'none': 0
}

WALK_SPEED = {'0.5': 20, '1.0': 40, '1.5': 60}
RUN_SPEED  = {'0.5': 40, '1.0': 70, '1.5': 90}

def generate_ev3(ir: list[dict]) -> str:
    lines = [
        "# Generated by Kobe — DO NOT EDIT",
        "from ev3dev2.motor import LargeMotor, OUTPUT_A, OUTPUT_B, SpeedPercent",
        "from ev3dev2.sensor.lego import UltrasonicSensor, ColorSensor, InfraredSensor, TouchSensor, GyroSensor",
        "from ev3dev2.sensor import INPUT_1, INPUT_2, INPUT_3, INPUT_4",
        "import time",
        "",
        "left  = LargeMotor(OUTPUT_A)",
        "right = LargeMotor(OUTPUT_B)",
        "us    = UltrasonicSensor(INPUT_1)",
        "cs    = ColorSensor(INPUT_2)",
        "ir    = InfraredSensor(INPUT_3)",
        "ts    = TouchSensor(INPUT_4)",
        "",
    ]

    emitter = EV3Emitter(lines)
    emitter.emit_all(ir)
    return '\n'.join(lines)


class EV3Emitter:
    def __init__(self, lines: list):
        self.lines  = lines
        self.indent = 0
        self.cond_stack = []

    def w(self, line: str):
        self.lines.append('    ' * self.indent + line)

    def emit_all(self, ir: list[dict]):
        i = 0
        while i < len(ir):
            instr = ir[i]
            op    = instr['op']

            if op == 'POLICY':
                self.w(f"# Policy: efficiency={instr['efficiency']} safety={instr['safety']} comfort={instr['comfort']} curiosity={instr['curiosity']}")

            elif op == 'WALK':
                spd = int(instr['speedMultiplier'] * 40)
                self.w(f"left.on(SpeedPercent({spd})); right.on(SpeedPercent({spd}))  # walk {instr['direction']}")

            elif op == 'RUN':
                spd = int(instr['speedMultiplier'] * 35)
                self.w(f"left.on(SpeedPercent({spd})); right.on(SpeedPercent({spd}))  # run {instr['direction']}")

            elif op == 'STOP':
                self.w("left.off(); right.off()")

            elif op == 'TURN':
                if instr['direction'] == 'left':
                    self.w("left.on_for_rotations(SpeedPercent(-30), 0.5)")
                else:
                    self.w("right.on_for_rotations(SpeedPercent(-30), 0.5)")

            elif op == 'WAIT':
                self.w(f"time.sleep({instr['durationMs'] / 1000})")

            elif op == 'SENSE':
                for sensor in instr['sensors']:
                    if sensor == 'dist':   self.w("_dist   = us.distance_centimeters")
                    if sensor == 'colour': self.w("_colour = cs.color")
                    if sensor == 'IR':     self.w("_ir     = ir.proximity")
                    if sensor == 'touch':  self.w("_touch  = ts.is_pressed")
                    if sensor == 'gyro':   self.w("_gyro   = gs.angle if 'gs' in dir() else 0")

            elif op == 'CMP_DIST':
                self.cond_stack.append(f"_dist {instr['comparator']} {instr['valueCm']}")

            elif op == 'CMP_COLOUR':
                ev3_colour = COLOUR_MAP.get(instr['colour'] if isinstance(instr['colour'], str) else 'none', 0)
                expr = f"_colour == {ev3_colour}"
                self.cond_stack.append(f"(not {expr})" if instr['negate'] else expr)

            elif op == 'CMP_TOUCH':
                self.cond_stack.append("_touch")

            elif op == 'CMP_IR':
                if instr['mode'] == 'detected':
                    self.cond_stack.append("_ir < 50")
                else:
                    self.cond_stack.append(f"_ir {instr['comparator']} {instr['value']}")

            elif op == 'AND':
                b = self.cond_stack.pop(); a = self.cond_stack.pop()
                self.cond_stack.append(f"({a} and {b})")

            elif op == 'OR':
                b = self.cond_stack.pop(); a = self.cond_stack.pop()
                self.cond_stack.append(f"({a} or {b})")

            elif op == 'NOT':
                a = self.cond_stack.pop()
                self.cond_stack.append(f"(not {a})")

            elif op == 'JUMP_IF_FALSE':
                cond = self.cond_stack.pop() if self.cond_stack else 'False'
                self.w(f"if {cond}:")
                self.indent += 1

            elif op == 'JUMP':
                self.indent = max(0, self.indent - 1)

            elif op == 'LOOP_START':
                self.w(f"for _i in range({instr['count']}):")
                self.indent += 1

            elif op == 'LOOP_END':
                self.indent = max(0, self.indent - 1)

            elif op == 'BREAK':
                self.w("break")

            elif op == 'HALT':
                self.w("left.off(); right.off()")

            i += 1

# codegen_rpi.py

COLOUR_RGB = {
    'red':    (255, 0,   0),
    'orange': (255, 165, 0),
    'yellow': (255, 255, 0),
    'green':  (0,   255, 0),
    'blue':   (0,   0,   255),
    'indigo': (75,  0,   130),
    'violet': (238, 130, 238),
    'white':  (255, 255, 255),
    'black':  (0,   0,   0),
    'none':   None
}

def generate_rpi(ir: list[dict]) -> str:
    lines = [
        "# Generated by Kobe — DO NOT EDIT",
        "import RPi.GPIO as GPIO",
        "import time",
        "import smbus2",
        "",
        "GPIO.setmode(GPIO.BCM)",
        "",
        "# HC-SR04 ultrasonic",
        "TRIG, ECHO = 23, 24",
        "GPIO.setup(TRIG, GPIO.OUT)",
        "GPIO.setup(ECHO, GPIO.IN)",
        "",
        "# L298N motor driver",
        "ENA, IN1, IN2 = 18, 23, 24",
        "ENB, IN3, IN4 = 25, 8,  7",
        "GPIO.setup([ENA, IN1, IN2, ENB, IN3, IN4], GPIO.OUT)",
        "pwm_a = GPIO.PWM(ENA, 1000); pwm_a.start(0)",
        "pwm_b = GPIO.PWM(ENB, 1000); pwm_b.start(0)",
        "",
        "def _read_dist():",
        "    GPIO.output(TRIG, True)",
        "    time.sleep(0.00001)",
        "    GPIO.output(TRIG, False)",
        "    while GPIO.input(ECHO) == 0: pass",
        "    start = time.time()",
        "    while GPIO.input(ECHO) == 1: pass",
        "    return ((time.time() - start) * 34300) / 2",
        "",
        "try:",
        "",
    ]

    emitter = RPiEmitter(lines, indent=1)
    emitter.emit_all(ir)

    lines += [
        "finally:",
        "    pwm_a.stop(); pwm_b.stop()",
        "    GPIO.cleanup()",
    ]

    return '\n'.join(lines)


class RPiEmitter:
    def __init__(self, lines: list, indent: int = 0):
        self.lines      = lines
        self.indent     = indent
        self.cond_stack = []

    def w(self, line: str):
        self.lines.append('    ' * self.indent + line)

    def emit_all(self, ir: list[dict]):
        i = 0
        while i < len(ir):
            instr = ir[i]
            op    = instr['op']

            if op == 'WALK':
                duty = int(instr['speedMultiplier'] * 40)
                self.w(f"pwm_a.ChangeDutyCycle({duty}); pwm_b.ChangeDutyCycle({duty})")

            elif op == 'RUN':
                duty = int(instr['speedMultiplier'] * 35)
                self.w(f"pwm_a.ChangeDutyCycle({duty}); pwm_b.ChangeDutyCycle({duty})")

            elif op == 'STOP':
                self.w("pwm_a.ChangeDutyCycle(0); pwm_b.ChangeDutyCycle(0)")

            elif op == 'WAIT':
                self.w(f"time.sleep({instr['durationMs'] / 1000})")

            elif op == 'SENSE':
                for sensor in instr['sensors']:
                    if sensor == 'dist':   self.w("_dist = _read_dist()")
                    if sensor == 'touch':  self.w("_touch = GPIO.input(TOUCH_PIN)")

            elif op == 'CMP_DIST':
                self.cond_stack.append(f"_dist {instr['comparator']} {instr['valueCm']}")

            elif op == 'CMP_TOUCH':
                self.cond_stack.append("_touch == GPIO.HIGH")

            elif op == 'AND':
                b = self.cond_stack.pop(); a = self.cond_stack.pop()
                self.cond_stack.append(f"({a} and {b})")

            elif op == 'OR':
                b = self.cond_stack.pop(); a = self.cond_stack.pop()
                self.cond_stack.append(f"({a} or {b})")

            elif op == 'NOT':
                self.cond_stack.append(f"(not {self.cond_stack.pop()})")

            elif op == 'JUMP_IF_FALSE':
                cond = self.cond_stack.pop() if self.cond_stack else 'False'
                self.w(f"if {cond}:")
                self.indent += 1

            elif op == 'JUMP':
                self.indent = max(1, self.indent - 1)

            elif op == 'LOOP_START':
                self.w(f"for _i in range({instr['count']}):")
                self.indent += 1

            elif op == 'LOOP_END':
                self.indent = max(1, self.indent - 1)

            elif op == 'BREAK':
                self.w("break")

            elif op == 'HALT':
                self.w("pwm_a.ChangeDutyCycle(0); pwm_b.ChangeDutyCycle(0)")

            i += 1